import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"], 
  variable: "--font-inter",
  display: "swap",
});



export const metadata: Metadata = {
  title: "Media Metrics",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${inter.variable} bg-black antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
